### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by Hizitok** [Ginsakura/MUSYNCSave#1]
问一下作者，到具体使用这个tool的时候，环境怎么配？运行文件需要放在特定文件夹吗？

**Comment by Hizitok** [comment]
可以写在readme里面吗？谢谢

**Comment by Hizitok** [comment]
还有，控制台收到game start的时候，能否清空控制台并且将先前数据自动保存到高精度延迟分析中？

**Comment by Hizitok** [comment]
高精度延迟分析中，建议增加功能，使得可以重命名数据

**Comment by Hizitok** [comment]
建议延迟分析的cmd中，将early改为蓝色，late改为红色，方便玩家在游玩过程中判断当前是否需要微调延迟

**Comment by Ginsakura** [comment]
> 建议延迟分析的cmd中，早点改成蓝色，晚点改成红色，方方便玩家在游戏过程中判断前是否需要微调延迟

好主意，但是实际上推荐延迟调整值在分析结果的标题栏，AvgDelay这个数值，默认AvgDelay是计算±90ms内的平均值，
配置文件中启用高精度delay可以变为±45ms内的平均值

**Comment by Ginsakura** [comment]
> 高精度延迟分析中，建议增加功能，使得可以重命名数据

有想法，但是目前在忙别的，最近几天我有好多东西全都出问题了

**Comment by Ginsakura** [comment]
> 还有，控制台收到game start的时候，能否清空控制台并且将先前数据自动保存到高精度延迟分析中？

这个我不太擅长，因为控制台内容是通过CSharp代码编写的，我也仅仅是会用而已，
其实，我并不能看懂游戏客户端的代码，`gamestart`是通过在谱面初始化的时候发送一个成绩为9999ms的tap来实现的（在谱面加载完成时，开始前）
所以控制台并不知道何时才是谱面结束。

**Comment by Ginsakura** [comment]
> 问一下作者，到具体使用这个tool的时候，环境怎么配？运行文件需要放在特定文件夹吗？

只要游戏客户端在`X:/Program Files/steam/steamapps/common/`、`X:/SteamLibrary/steamapps/common/`、`X:/steam/steamapps/common/`目录下都可以被自动识别到（X指任意盘符），这三个目录是steam的默认游戏安装目录

*** 直接执行其中的可执行文件即可 ***

需要首次运行释放一些程序资源，
可以根据需要修改配置文件内的相应项目，我用了很长的名字应该比较好判断每条配置的用途吧？

*** 配置文件是json格式 ***

剩下的只要运行就可以了，release里的可执行文件可以直接执行，环境都带的有，all in one就是字面意思，with console与no console也是字面意思，四个只需要选看着顺眼的一个使用，`建议放到一个单独的文件夹里`，因为程序运行会释放出一些文件，虽然都在`musync_data`文件夹里

**Comment by Ginsakura** [comment]
> 建议延迟分析的cmd中，早点改成蓝色，晚点改成红色，方方便玩家在游戏过程中判断前是否需要微调延迟

我目前的区分方法是±5ms、±10ms、±45ms、±90ms、±150ms、150ms+，通过颜色来让玩家看出当前击打大概处于什么评级
你说的在理，但是还需要再设计一下颜色

tips：我对Csharp并不熟悉

**Comment by Ginsakura** [comment]
> 还有，控制台收到game start的时候，能否清空控制台并且将先前数据自动保存到高精度延迟分析中？

这个其实直接把控制台里的数据Ctrl+A、Ctrl+C，然后Ctrl+V粘贴进分析框就行，我在分析软件里写了找到最后一个gamestart再分析之后的HitDelay

也就是说，前面的数据不会产生干扰，只要gamestart正常出现

每次gamestart就是一个分界点，最后一个gamestart之前的数据全都跳过，从最后一个gamestart开始读数据

**Comment by Ginsakura** [comment]
我有第一个issue了好耶ヽ(✿ﾟ▽ﾟ)ノ

感谢使用本程序，有哪点没有用明白可以继续发，我目前写好的使用文档简直就像是不可名状之物一样，通过问答形式介绍会更清晰一点？

我尽快更新（最近qqbot炸了、MicroSoft E5账户炸了、手机上太极框架里的QQ也炸了）

**Comment by zerofdest** [comment]
使用体验很好，感谢大佬的持续更新

**Comment by AXn233** [comment]
为什么我在解码存档的环节下exe程序直接卡死不动了呢？，用noconsole的程序直接给我弹了一个cmd窗口，按了一下后程序就直接结束了

**Comment by Ginsakura** [comment]
> 为什么我在解码存档的环节下exe程序直接卡死不动了呢？，用noconsole的程序直接给我弹了一个cmd窗口，按了一下后程序就直接结束了

请下载带控制台版本的软件，然后提供一下控制台中的输出，尽量使用代码格式，你光这样说我也没法虚空debug吖）
例子：

\`\`\`cmd
psutil.NoSuchProcess(pid=3368, msg='process PID not found')
psutil.NoSuchProcess(pid=14472, msg='process PID not found')
DataLoad Run Time: 468.347300 ms
CheckGameIsStart Run Time: 1077.555600 ms
   Local Json Version: 20240430
  Terget Json Version: 20240430
CheckJsonUpdate Run Time: 2494.311200 ms
  Terget Version : 1.2.6.3
   Local Version : 1.2.6.3
Local PreVersion : 1.2.6.7
CheckUpdate Run Time: 3254.497300 ms
psutil.NoSuchProcess(pid=3652, msg='process PID not found')
CheckGameIsStart Run Time: 674.244100 ms
\`\`\`

**Comment by AXn233** [comment]
UnicodeDecodeError('utf-8', b'\xac', 0, 1, 'invalid start byte')
请按任意键继续. . . Exception in thread Thread-2 (CheckGameIsStart):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "MainWindowOldStyle.py", line 189, in CheckGameIsStart
  File "tkinter\__init__.py", line 1713, in __setitem__
  File "tkinter\__init__.py", line 1702, in configure
  File "tkinter\__init__.py", line 1692, in _configure
RuntimeError: main thread is not in main loop
Exception in thread Thread-3 (CheckJsonUpdate):
Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 205, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002BE15B8ED10>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Ginsakura/MUSYNCSave/main/musync_data/songname.update (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BE15B8ED10>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MainWindowOldStyle.py", line 359, in CheckJsonUpdate
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Ginsakura/MUSYNCSave/main/musync_data/songname.update (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BE15B8ED10>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "MainWindowOldStyle.py", line 373, in CheckJsonUpdate
  File "tkinter\messagebox.py", line 98, in showerror
  File "tkinter\messagebox.py", line 76, in _show
  File "tkinter\commondialog.py", line 45, in show
RuntimeError: main thread is not in main loop
  Terget Version : 1.2.7.1
   Local Version : 1.2.6.3
Local PreVersion : 1.2.6.7
Exception in thread Thread-4 (CheckUpdate):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "MainWindowOldStyle.py", line 393, in CheckUpdate
  File "tkinter\__init__.py", line 1702, in configure
  File "tkinter\__init__.py", line 1692, in _configure
RuntimeError: main thread is not in main loop

**Comment by Ginsakura** [comment]
额……总感觉前面好像还少了什么……
能否通过
```powershell
.\MusyncSavDecodeGUI.exe > log.txt
```
的命令将日志输出到文件，然后提交日志附件？
如果不想继续调试的话……试着下载最新的版本看看？

**Comment by AXn233** [comment]
[log.txt](https://github.com/user-attachments/files/16610340/log.txt)

**Comment by Ginsakura** [comment]
我大概懂了，是存档解析的问题，请问能提供一下存档文件吗？
你的存档结构与我这边收集的几个存档之间有点差异
以及，确认您是Steam平台的喵赛克？
Epic平台因为我没买，所以没有Epic平台的存档，也没有针对Epic平台的游戏进行适配

**Comment by Ginsakura** [comment]
![image](https://github.com/user-attachments/assets/c8dff622-0ee2-4b97-8201-89215c8cbf6d)
这是我这边存档解析的开头部分

**Comment by AXn233** [comment]
[savedata.zip](https://github.com/user-attachments/files/16613192/savedata.zip)
我这边正好有epic版的喵赛克 我直接都发过来了

**Comment by Ginsakura** [comment]
![image](https://github.com/user-attachments/assets/df336e71-6915-4fc2-ae93-72ae81dc12ac)
完成了对你的存档的兼容，请等待1.6.7rc2版本，稍后将发送到自动构建
我再修点别的bug
![image](https://github.com/user-attachments/assets/f7c9cc93-a773-4596-9c29-765b5c0643ea)
核对一下成绩？
