### ISSUE TITLE
[BUG] 成绩分布

### ISSUE THREAD

**Issue by AXn233** [Ginsakura/MUSYNCSave#3]
** 问题描述 **
成绩分布中，若6k或者4k没有游玩数据，score[0]||score[1]会因为没有数据而导致无法调出难度与分数散点图

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "MainWindowOldStyle.py", line 123, in <lambda>
    self.difficuteScoreAnalyze = Button(self.root, text="成绩分布",command=lambda:dsa.Analyze(), font=self.font)
                                                                                  ^^^^^^^^^^^^^
  File "Difficulty_ScoreAnalyze.py", line 48, in Analyze
    minScore = int(min([min(score[0]),min(score[1])]))
                                      ^^^^^^^^^^^^^
ValueError: min() iterable argument is empty

**Comment by Ginsakura** [comment]
你的意思是……你只玩过4K/6K的其中一种模式，另一种模式一点也没有碰过是吗？
（挠头）
